/**
 * Ibadan areas with coordinates and driving distance from Bodija Market.
 * Generated by scripts/build-ibadan-areas.js — do not hand-edit, rerun instead.
 *
 * Coordinates come from OpenStreetMap; roadKm is real driving distance from
 * the OpenRouteService Matrix API. Both are resolved at build time because the
 * area list is fixed, so these values are constants — the running app makes no
 * geocoding or routing calls to price a known area.
 *
 * Delivery fees are computed from roadKm, so these are money-critical numbers.
 *
 * Data (c) OpenStreetMap contributors, ODbL 1.0 — https://osm.org/copyright
 * Routing (c) openrouteservice.org by HeiGIT | OpenStreetMap contributors
 */
export interface IbadanArea {
  name: string;
  lat: number;
  lng: number;
  /** Driving km from Bodija Market. */
  roadKm: number;
  /** True when routing was unavailable and this is a straight-line estimate. */
  approx?: boolean;
}

export const IBADAN_AREA_COORDS: IbadanArea[] = [
  { name: "Bodija", lat: 7.439915, lng: 3.920187, roadKm: 0.86, approx: true },
  { name: "New Bodija", lat: 7.4235427, lng: 3.9153632, roadKm: 1.79, approx: true },
  { name: "Bodija Market", lat: 7.4359015, lng: 3.9157404, roadKm: 0, approx: true },
  { name: "Agodi", lat: 7.3977091, lng: 3.9218427, roadKm: 5.59, approx: true },
  { name: "Agodi Gate", lat: 7.3977091, lng: 3.9218427, roadKm: 5.59, approx: true },
  { name: "Akobo", lat: 7.4336631, lng: 3.9434411, roadKm: 3.98, approx: true },
  { name: "Aleshinloye", lat: 7.3894283, lng: 3.8700502, roadKm: 9.38, approx: true },
  { name: "Basorun", lat: 7.4223423, lng: 3.9357891, roadKm: 3.48, approx: true },
  { name: "Beere", lat: 7.3794191, lng: 3.8989033, roadKm: 8.51, approx: true },
  { name: "Challenge", lat: 7.3469925, lng: 3.8783092, roadKm: 13.93, approx: true },
  { name: "Dugbe", lat: 7.3875447, lng: 3.87909, roadKm: 8.74, approx: true },
  { name: "Eleyele", lat: 7.4069688, lng: 3.860646, roadKm: 8.94, approx: true },
  { name: "Felele", lat: 7.3454294, lng: 3.8847906, roadKm: 13.81, approx: true },
  { name: "Gbagi", lat: 7.39337, lng: 3.9558975, roadKm: 8.42, approx: true },
  { name: "Idi Ape", lat: 7.401532, lng: 3.925715, roadKm: 5.17, approx: true },
  { name: "Iwo Road", lat: 7.4034802, lng: 3.9411321, roadKm: 5.93, approx: true },
  { name: "Jericho", lat: 7.3948226, lng: 3.8647556, roadKm: 9.42, approx: true },
  { name: "Molete", lat: 7.3611282, lng: 3.8891606, roadKm: 11.46, approx: true },
  { name: "Mokola", lat: 7.39883, lng: 3.888293, roadKm: 6.65, approx: true },
  { name: "Moniya", lat: 7.522265, lng: 3.912367, roadKm: 12.49, approx: true },
  { name: "Ojoo", lat: 7.5231043, lng: 3.9578937, roadKm: 13.98, approx: true },
  { name: "Oluyole", lat: 7.3650612, lng: 3.861981, roadKm: 12.82, approx: true },
  { name: "Onireke", lat: 7.4057885, lng: 3.904762, roadKm: 4.63, approx: true },
  { name: "Orogun", lat: 7.4512499, lng: 3.9209739, roadKm: 2.34, approx: true },
  { name: "Oke Ado", lat: 7.378138, lng: 3.87972, roadKm: 9.82, approx: true },
  { name: "Oke Bola", lat: 7.3834626, lng: 3.8775912, roadKm: 9.35, approx: true },
  { name: "Olodo", lat: 7.417875, lng: 4.013397, roadKm: 14.24, approx: true },
  { name: "Podo", lat: 7.3077565, lng: 3.8732233, roadKm: 19.5, approx: true },
  { name: "Ring Road", lat: 7.3586072, lng: 3.8716892, roadKm: 12.83, approx: true },
  { name: "Sango", lat: 7.4240991, lng: 3.8989269, roadKm: 2.95, approx: true },
  { name: "Samonda", lat: 7.4306482, lng: 3.9081438, roadKm: 1.33, approx: true },
  { name: "Yemetu", lat: 7.3875362, lng: 3.9046838, roadKm: 7.17, approx: true },
  { name: "Agbowo", lat: 7.4466913, lng: 3.9137314, roadKm: 1.59, approx: true },
  { name: "Total Garden", lat: 7.411437, lng: 3.90817, roadKm: 3.7, approx: true },
  { name: "Adamasingba", lat: 7.396143, lng: 3.886918, roadKm: 7.08, approx: true },
  { name: "Omi Adio", lat: 7.4090655, lng: 3.7474278, roadKm: 24.44, approx: true },
  { name: "Kudeti", lat: 7.3740865, lng: 3.9040952, roadKm: 9.09, approx: true },
  { name: "Agugu", lat: 7.3865884, lng: 3.9272598, roadKm: 7.32, approx: true },
  { name: "Aperin", lat: 7.3673663, lng: 3.9118141, roadKm: 9.92, approx: true },
  { name: "Odinjo", lat: 7.3591358, lng: 3.9132018, roadKm: 11.1, approx: true },
  { name: "Olomi", lat: 7.3585244, lng: 3.9088049, roadKm: 11.23, approx: true },
  { name: "Alalubosa", lat: 7.3838636, lng: 3.8616657, roadKm: 10.8, approx: true },
  { name: "Oja Oba", lat: 7.3742579, lng: 3.8951313, roadKm: 9.39, approx: true },
  { name: "Ijokodo", lat: 7.4266059, lng: 3.8835902, roadKm: 4.8, approx: true },
  { name: "Poly Road", lat: 7.4256516, lng: 3.8905524, roadKm: 3.9, approx: true },
  { name: "Ashi", lat: 7.431187, lng: 3.9261626, roadKm: 1.64, approx: true },
  { name: "Awotan", lat: 7.450043, lng: 3.87046, roadKm: 6.8, approx: true },
  { name: "Apete", lat: 7.450043, lng: 3.87046, roadKm: 6.8, approx: true },
  { name: "University of Ibadan", lat: 7.4477245, lng: 3.8967116, roadKm: 3.22, approx: true },
  { name: "University College Hospital", lat: 7.4028275, lng: 3.9037086, roadKm: 5.08, approx: true },
  { name: "Lekan Salami Stadium", lat: 7.3963017, lng: 3.8853064, roadKm: 7.2, approx: true },
  { name: "Cocoa House", lat: 7.3880524, lng: 3.8788769, roadKm: 8.7, approx: true },
  { name: "Mapo Hall", lat: 7.3759998, lng: 3.8969774, roadKm: 9.07, approx: true },
  { name: "Agodi Gardens", lat: 7.4093254, lng: 3.8982644, roadKm: 4.59, approx: true },
  { name: "Alakia", lat: 7.3908284, lng: 3.9738165, roadKm: 10.57, approx: true },
  { name: "Egbeda", lat: 7.3926447, lng: 4.0387216, roadKm: 18.7, approx: true },
];
