/**
 * Ibadan areas with coordinates and driving distance from Bodija Market.
 * Generated by scripts/build-ibadan-areas.js — do not hand-edit, rerun instead.
 *
 * Coordinates come from OpenStreetMap; roadKm is real driving distance from
 * the OpenRouteService Matrix API. Both are resolved at build time because the
 * area list is fixed, so these values are constants — the running app makes no
 * geocoding or routing calls to price a known area.
 *
 * Delivery fees are computed from roadKm, so these are money-critical numbers.
 *
 * Data (c) OpenStreetMap contributors, ODbL 1.0 — https://osm.org/copyright
 * Routing (c) openrouteservice.org by HeiGIT | OpenStreetMap contributors
 */
export interface IbadanArea {
  name: string;
  lat: number;
  lng: number;
  /** Driving km from Bodija Market. */
  roadKm: number;
  /** True when routing was unavailable and this is a straight-line estimate. */
  approx?: boolean;
}

export const IBADAN_AREA_COORDS: IbadanArea[] = [
  { name: "Bodija", lat: 7.439915, lng: 3.920187, roadKm: 1.2 },
  { name: "New Bodija", lat: 7.4235427, lng: 3.9153632, roadKm: 2.1 },
  { name: "Bodija Market", lat: 7.4359015, lng: 3.9157404, roadKm: 0 },
  { name: "Agodi", lat: 7.3977091, lng: 3.9218427, roadKm: 6.34 },
  { name: "Agodi Gate", lat: 7.3977091, lng: 3.9218427, roadKm: 6.34 },
  { name: "Akobo", lat: 7.4336631, lng: 3.9434411, roadKm: 6.39 },
  { name: "Aleshinloye", lat: 7.3894283, lng: 3.8700502, roadKm: 9.27 },
  { name: "Basorun", lat: 7.4223423, lng: 3.9357891, roadKm: 6.04 },
  { name: "Beere", lat: 7.3794191, lng: 3.8989033, roadKm: 7.47 },
  { name: "Challenge", lat: 7.3469925, lng: 3.8783092, roadKm: 11.93 },
  { name: "Dugbe", lat: 7.3875447, lng: 3.87909, roadKm: 8.45 },
  { name: "Eleyele", lat: 7.4069688, lng: 3.860646, roadKm: 11.54 },
  { name: "Felele", lat: 7.3454294, lng: 3.8847906, roadKm: 12.29 },
  { name: "Gbagi", lat: 7.39337, lng: 3.9558975, roadKm: 8.18 },
  { name: "Idi Ape", lat: 7.401532, lng: 3.925715, roadKm: 7.04 },
  { name: "Iwo Road", lat: 7.4034802, lng: 3.9411321, roadKm: 6.39 },
  { name: "Jericho", lat: 7.3948226, lng: 3.8647556, roadKm: 10.54 },
  { name: "Molete", lat: 7.3611282, lng: 3.8891606, roadKm: 10.08 },
  { name: "Mokola", lat: 7.39883, lng: 3.888293, roadKm: 6.49 },
  { name: "Moniya", lat: 7.522265, lng: 3.912367, roadKm: 11.19 },
  { name: "Ojoo", lat: 7.5231043, lng: 3.9578937, roadKm: 13.69 },
  { name: "Oluyole", lat: 7.3650612, lng: 3.861981, roadKm: 12.17 },
  { name: "Onireke", lat: 7.4057885, lng: 3.904762, roadKm: 5.78 },
  { name: "Orogun", lat: 7.4512499, lng: 3.9209739, roadKm: 9.71 },
  { name: "Oke Ado", lat: 7.378138, lng: 3.87972, roadKm: 9.64 },
  { name: "Oke Bola", lat: 7.3834626, lng: 3.8775912, roadKm: 9.42 },
  { name: "Olodo", lat: 7.417875, lng: 4.013397, roadKm: 18.91 },
  { name: "Podo", lat: 7.3077565, lng: 3.8732233, roadKm: 23.39 },
  { name: "Ring Road", lat: 7.3586072, lng: 3.8716892, roadKm: 13.18 },
  { name: "Sango", lat: 7.4240991, lng: 3.8989269, roadKm: 3.55 },
  { name: "Samonda", lat: 7.4306482, lng: 3.9081438, roadKm: 1.53 },
  { name: "Yemetu", lat: 7.3875362, lng: 3.9046838, roadKm: 6.18 },
  { name: "Agbowo", lat: 7.4466913, lng: 3.9137314, roadKm: 2.69 },
  { name: "Total Garden", lat: 7.411437, lng: 3.90817, roadKm: 3.7 },
  { name: "Adamasingba", lat: 7.396143, lng: 3.886918, roadKm: 6.83 },
  { name: "Omi Adio", lat: 7.4090655, lng: 3.7474278, roadKm: 27.98 },
  { name: "Kudeti", lat: 7.3740865, lng: 3.9040952, roadKm: 8.59 },
  { name: "Agugu", lat: 7.3865884, lng: 3.9272598, roadKm: 7.8 },
  { name: "Aperin", lat: 7.3673663, lng: 3.9118141, roadKm: 9.58 },
  { name: "Odinjo", lat: 7.3591358, lng: 3.9132018, roadKm: 10.55 },
  { name: "Olomi", lat: 7.3585244, lng: 3.9088049, roadKm: 10.27 },
  { name: "Alalubosa", lat: 7.3838636, lng: 3.8616657, roadKm: 10.4 },
  { name: "Oja Oba", lat: 7.3742579, lng: 3.8951313, roadKm: 8.23 },
  { name: "Ijokodo", lat: 7.4266059, lng: 3.8835902, roadKm: 5.57 },
  { name: "Poly Road", lat: 7.4256516, lng: 3.8905524, roadKm: 5.01 },
  { name: "Ashi", lat: 7.431187, lng: 3.9261626, roadKm: 3.71 },
  { name: "Awotan", lat: 7.450043, lng: 3.87046, roadKm: 9.39 },
  { name: "Apete", lat: 7.450043, lng: 3.87046, roadKm: 9.39 },
  { name: "University of Ibadan", lat: 7.4477245, lng: 3.8967116, roadKm: 3.14 },
  { name: "University College Hospital", lat: 7.4028275, lng: 3.9037086, roadKm: 5.13 },
  { name: "Lekan Salami Stadium", lat: 7.3963017, lng: 3.8853064, roadKm: 7.18 },
  { name: "Cocoa House", lat: 7.3880524, lng: 3.8788769, roadKm: 8.45 },
  { name: "Mapo Hall", lat: 7.3759998, lng: 3.8969774, roadKm: 7.91 },
  { name: "Agodi Gardens", lat: 7.4093254, lng: 3.8982644, roadKm: 5.62 },
  { name: "Alakia", lat: 7.3908284, lng: 3.9738165, roadKm: 10.14 },
  { name: "Egbeda", lat: 7.3926447, lng: 4.0387216, roadKm: 18.43 },
];
